CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    customer_name TEXT,
    city TEXT,
    signup_date DATE,
    customer_segment VARCHAR(50)
);

CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    product_name TEXT,
    category TEXT,
    unit_price INT
);

CREATE TABLE orders (
    order_id SERIAL PRIMARY KEY,
    order_date DATE,
    customer_id INT REFERENCES customers(customer_id),
    product_id INT REFERENCES products(product_id),
    quantity INT,
    order_status TEXT
);

CREATE TABLE payments (
    payment_id SERIAL PRIMARY KEY,
    order_id INT REFERENCES orders(order_id),
    payment_amount INT,
    payment_status TEXT,
    payment_date DATE
);
select * from customers
select * from products
select * from orders
select * from payments

--Show all customers who have placed an order.
select customer_name,city
from customers c
join orders o 
on c.customer_id=o.customer_id

--Q2 — Orders with Product Details
select quantity,order_id, product_name,category
from products p
join orders o 
on p.product_id=o.product_id

--Q3 — Customer + Product
select customer_name,product_name 
from customers c 
join orders o
on c.customer_id=o.customer_id
join products p
on o.product_id=p.product_id

--Q5 — Find all delivered orders 
select product_name,order_status
from products p
join orders o
on o.product_id=p.product_id
where order_status ='Delivered'
--Q6 — Find orders placed by customers belonging to the Corporate segment

select customer_name,customer_Segment
from customers c
join orders o
on o.customer_id=c.customer_id
where customer_segment='Corporate'

--Q7 — Total Orders by Customer Find the number of orders placed by each customer
select customer_name,count(order_status)as total_orders
from customers c
join orders o 
on c.customer_id=o.customer_id
group by customer_name

--Q10 — Find total quantity sold for every product.

select product_name,sum(quantity) as total_quantity
from products p
join orders o
on p.product_id=o.product_id
group by product_name

--Q.11 --find total revenue for each product
select p.product_name,sum(o.quantity*p.unit_price)as total_revenue
from products p
join orders o 
on p.product_id=o.product_id
group by product_name

--Q.12-- Calculate total order value for each customer.

select c.customer_name,sum(o.quantity*p.unit_price)as total_order_Value
from customers c
join orders o
on c.customer_id=o.customer_id
join products p
on o.product_id=p.product_id
group by customer_name

--Q.13 Calculate total revenue generated by each product category.

select p.category,sum(o.quantity*p.unit_price)as total_revenue
from products p
join orders o
on p.product_id=o.product_id
group by category

--Q.14 Find customers who have never placed an order.
select c.customer_name ,o.order_id
from customers c
left join orders o
on c.customer_id=o.customer_id 
where o.order_id is null

--Q.15 Find products that have never appeared in the orders table.
select p.product_name,o.order_id
from products p
left join orders o
on p.product_id=o.product_id
where o.order_id is null

--Q.16 Find customers who have placed more than one order.

select c.customer_name,count(o.order_id)as total_orders
from customers c
left join orders o
on c.customer_id=o.customer_id
group by customer_name
having count(o.order_id)>1

--Q.17-Calculate total revenue per customer and identify the customer with the highest total order value.

select c.customer_name,sum(o.quantity*p.unit_price)as total_revenue
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p
on p.product_id=o.product_id
group by customer_name 
order by sum(o.quantity*p.unit_price) desc

--Q.18 Find the product generating the highest total revenue.
select p.product_name,sum(o.quantity*p.unit_price)as total_revenue
from products p
join orders o 
on p.product_id=o.product_id
group by product_name
order by sum(o.quantity*p.unit_price) desc limit 1

--These are closer to business problem solving, rather than simply testing whether you know JOIN syntax.
--Q19 — Customer Segment Revenue
--Calculate total revenue generated by each customer segment.
select * from customers
select * from products
select * from orders
select * from payments

select c.customer_segment,sum(o.quantity*p.unit_price)as total_revenue
from customers c
join orders o
on c.customer_id=o.customer_id
join products p
on p.product_id=o.product_id
group by customer_segment
order by sum(o.quantity*p.unit_price) desc

--Q20 — Segment-wise Order Volume
--For each customer segment, calculate:
--•	Number of orders 
--•	Total quantity ordered 
--•	Total revenue 

select c.customer_segment, count(o.order_id)as total_orders,
sum(o.quantity)as total_quantity,
sum(o.quantity*p.unit_price)as total_revenue
from customers c 
join orders o
on c.customer_id=o.customer_id
join products p
on p.product_id=o.product_id
group by customer_segment 

--Q21 — Delivered vs Cancelled Revenue
--Calculate revenue separately for each order status.
--Output:
--order_status
--total_orders
--total_revenue

select order_status,count(o.order_id)as total_orders,
sum(o.quantity*p.unit_price)as total_revenue
from orders o
join products p
on o.product_id=p.product_id
group by order_status

--Q22 — Payment Coverage
--Find orders where the payment amount does not equal:
--quantity × unit_price
--Return:
--order_id
--product_name
--quantity
--expected_amount

select o.order_id,p.product_name,o.quantity,pp.payment_amount,
(o.quantity*p.unit_price)as expected_amount
from orders o
join payments pp
on o.order_id=pp.order_id
join products p
on o.product_id=p.product_id
where payment_amount <> (o.quantity*p.unit_price)

--Q23 — Customers With Unpaid/Pending Payments
--Find customers who have at least one order whose payment status is Pending.
--Return:
--customer_name
--order_id
--payment_amount
--payment_status
SELECT 
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN payments pp
    ON o.order_id = pp.order_id
WHERE pp.payment_status = 'pending'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1;

--Q24 — City-wise Revenue
--Calculate total revenue generated from each customer city.
select c.city,sum(o.quantity*p.unit_price)as total_revenue
from customers c
join orders o
on c.customer_id=o.customer_id
join products p
on p.product_id=o.product_id
group by city 
order by sum(o.quantity*p.unit_price) desc

--Q25 — Calculate:Average Order Value for each customer segment.

select customer_segment,
sum(o.quantity*p.unit_price)as total_revenue,
count(order_id)as total_orders,
( sum(o.quantity*p.unit_price)/count(order_id))as avg_order_value
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p
on p.product_id=o.product_id
group by customer_segment 

--Q.26 Find customers who placed 2 or more orders.
select c.customer_name,count(o.order_id)as total_orders
from customers c
left join orders o 
on c.customer_id=o.customer_id
group by customer_name
having count(o.order_id)>=2

--Q.27 Q27 — Product Performance
--For every product, calculate:
--•	Number of orders 
--•	Total quantity sold 
--•	Total revenue 
--•	Average selling value per order 
select p.product_name,p.product_id,
count(o.order_id)as total_orders,
sum(o.quantity)as total_quantity,
sum(o.quantity*p.unit_price)as total_revenue,
( sum(o.quantity*p.unit_price)/count(order_id))as avg_order_value
from products p 
join orders o 
on o.product_id=p.product_id
group by p.product_name,p.product_id

--Q.28  Q28 — Customer Purchase Pattern
--For each customer, show:
--•	Customer name 
--•	Segment 
--•	Number of distinct products purchased 
--•	Total quantity purchased 
--•	Total revenue
select c.customer_name,c.customer_segment,
count(distinct o.order_id)as product_purchased,
sum(o.quantity)as total_quantity,
sum(o.quantity*p.unit_price)as total_revenue
from customers c
join orders o
on c.customer_id=o.customer_id
join products p
on o.product_id=p.product_id
group by c.customer_name,c.customer_segment

--Q29 — Top Customer in Each Segment
--Find the customer generating the highest revenue within each customer segment
with ranked as (
select c.customer_name,c.customer_segment,
sum(o.quantity*p.unit_price)as total_revenue,
rank()over(partition by customer_segment order by sum(o.quantity*p.unit_price) desc)as ranked
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p
on o.product_id=p.product_id
group by c.customer_name,c.customer_segment
order by sum(o.quantity*p.unit_price) desc
)
select customer_name,customer_segment,total_revenue,ranked
from ranked
where ranked=1;

--Q30 — Most Popular Product by Quantity
--Find the product within each categroy the highest total quantity sold.
with product_top as(
select p.product_name,p.category,sum(o.quantity)as total_ordered,
rank()over (partition by category order by sum(o.quantity) desc )as ranked 
from products p
join orders o 
on o.product_id=p.product_id
group by product_name,category
)
select product_name,total_ordered,category,ranked
from product_top
where ranked=1;

--Q31 — Most Popular Product by Quantity

WITH product_top AS (
 SELECT p.product_name, p.category,
 SUM(o.quantity) AS total_ordered,
 RANK() OVER ( ORDER BY SUM(o.quantity) DESC) AS ranked
 FROM products p
 JOIN orders o
 ON o.product_id = p.product_id
GROUP BY p.product_name, p.category
)
SELECT
    product_name,
    category,
    total_ordered
FROM product_top
WHERE ranked = 1;

--Q31 — Customers Buying Multiple Categories
--Find customers who have purchased products from more than one category
select c.customer_name,count(distinct p.category)as category_Count
from customers c
join orders o 
on o.customer_id=c.customer_id
join products p
on p.product_id=o.product_id
group by customer_name
order by count(distinct p.category) desc

---------------OR--------------------------
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT p.category) AS category_count,
    STRING_AGG(DISTINCT p.category, ', ') AS categories_purchased
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN products p
    ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT p.category) > 1;

--Q32 — Segment × Category Analysis
--Calculate revenue for every combination of:
--customer_segment and category
select c.customer_segment,p.category, sum(o.quantity*p.unit_price)as total_revenue
from customers c
inner join orders o
on c.customer_id=o.customer_id
inner join products p
on p.product_id=o.product_id
group by c.customer_segment,p.category

--Q33 — Payment Status Analysis
--For each payment status, calculate:
--•	Number of payments 
--•	Total payment amount 
--•	Average payment amount 
select payment_status,sum(payment_amount)as total_amount,
count(payment_id)as count_of_payment,
(sum(payment_amount)/count(payment_id))as average_pay_amount
from payments 
group by payment_status

--Q34 — Revenue Leakage Check
--Identify orders where:
--payment_amount < quantity × unit_price
with revenue as (
select o.order_id, sum(o.quantity*p.unit_price)as total_revenue,pp.payment_amount
from orders o
join products p
on o.product_id=p.product_id
join payments pp
on o.order_id=pp.order_id
group by o.order_id,pp.payment_amount
),difference as (
select order_id,total_revenue,payment_amount,
(total_revenue-payment_amount)as differences
from revenue
) select order_id,total_revenue,payment_amount,differences 
from difference 
where payment_amount<total_revenue

--Q35 — Complete Business Dashboard Query
select c.customer_name,c.customer_segment,c.city ,
 sum(o.quantity*p.unit_price)as total_revenue,
 sum(o.quantity)as total_quantity,
 count(o.order_id)as total_orders,
 coalesce(sum(pp.payment_amount)filter (where pp. payment_status='Paid'),0)as total_paid,
 coalesce (sum(pp.payment_amount)filter (where pp.payment_status='Pending'),0)as total_pending
 from customers c
 join orders o 
 on c.customer_id=o.customer_id
 join products p
 on o.product_id=p.product_id
 join payments pp
 on o.order_id=pp.order_id
 group by c.customer_name,c.customer_segment,c.city
 





















































































